ktor:
  deployment:
    port: 8080
    host: 0.0.0.0
  application:
    modules:
      - com.bieniucieniu.ApplicationKt.module
  development: true
koog:
  ollama:
    enable: true
    baseUrl: ${OLLAMA_BASE_URL}
    baseUrlRealm: ${?OLLAMA_BASE_URL_REALM}
    model: llama3.2:3b
    username: ${OLLAMA_USERNAME}
    password: ${OLLAMA_PASSWORD}
  google:
    apikey: ${GOOGLE_API_KEY}
    baseUrl: https://generativelanguage.googleapis.com
oauth2:
  google:
    client_id: ${GOOGLE_CLIENT_ID}
    client_secret: ${GOOGLE_CLIENT_SECRET}