ktor:
  deployment:
    port: 8080
    host: 0.0.0.0
  application:
    modules:
      - com.bieniucieniu.ApplicationKt.module
  development: true
ai:
  ollama:
    baseUrl: ${?OLLAMA_BASE_URL}
    baseUrlRealm: ${?OLLAMA_BASE_URL_REALM}
    model: llama3.2:3b
    models:
      - llama3.2:3b
      - gemma3:4b
    username: ${?OLLAMA_USERNAME}
    password: ${?OLLAMA_PASSWORD}
  google:
    apikey: ${?GOOGLE_API_KEY}
oauth2:
  google:
    clientId: ${GOOGLE_CLIENT_ID}
    clientSecret: ${GOOGLE_CLIENT_SECRET}
database:
  database: ${DATABASE_DATABASE}
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  url: ${DATABASE_URL}
